/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacrudapplication;
import java.awt.HeadlessException;
import java.util.List;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CIFIT
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     * @throws java.sql.SQLException
     */
    private int selectedUserId = -1;
    
    public CRUD() throws SQLException{
        initComponents();
        loadUsers();
        setResizable(false); // Corrected method call
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fNameTexted = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lNameTexted = new javax.swing.JTextField();
        emailTexted = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        countryTexted = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        addSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java CRUD Application");
        setSize(new java.awt.Dimension(600, 450));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Java CRUD Application");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frist Name");

        fNameTexted.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");

        lNameTexted.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        emailTexted.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        countryTexted.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Country");

        update.setBackground(new java.awt.Color(255, 255, 0));
        update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 51, 0));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        addSubmit.setBackground(new java.awt.Color(0, 204, 0));
        addSubmit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addSubmit.setForeground(new java.awt.Color(255, 255, 255));
        addSubmit.setText("add");
        addSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSubmitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(countryTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lNameTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(addSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTexted, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public final void loadUsers()throws SQLException {
        UserDAO userDAO = new UserDAO();
        List<UserModel> users = userDAO.getUsers();
        String[][] data = new String[users.size()][5];
        
        for(int i=0; i<users.size(); i++) {
            data[i][0] = String.valueOf(users.get(i).getId());
            data[i][1] = users.get(i).getFristName();
            data[i][2] = users.get(i).getLastName();
            data[i][3] = users.get(i).getEmail();
            data[i][4] = users.get(i).getCountry();
        }
        String[] columName = {"ID", "Frist Name", "Last Name", "Email", "Country"};
        usersTable.setModel(new javax.swing.table.DefaultTableModel(data, columName));
    }
    
    public void clearForm(){
        fNameTexted.setText("");
        lNameTexted.setText("");
        emailTexted.setText("");
        countryTexted.setText("");
    }
    private void addSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSubmitMouseClicked
        final String fristName = fNameTexted.getText();
        final String lastName = lNameTexted.getText();
        final String email = emailTexted.getText();
        final String country = countryTexted.getText();
                
        UserDAO userDao;
        UserModel newUser = new UserModel(0, fristName, lastName, email, country);
        try{
            
            if(fristName.isEmpty()){
            JOptionPane.showMessageDialog(this, "first name is required", "error", JOptionPane.ERROR_MESSAGE);
            } else if(lastName.isEmpty()){
                JOptionPane.showMessageDialog(this, "last name is required", "error", JOptionPane.ERROR_MESSAGE);
            } else if(email.isEmpty()){
                JOptionPane.showMessageDialog(this, "email is required", "error", JOptionPane.ERROR_MESSAGE);
            }else if(country.isEmpty()){
                JOptionPane.showMessageDialog(this, "country is required", "error", JOptionPane.ERROR_MESSAGE);
            }else{
                userDao = new UserDAO();
                int result = userDao.insertUser(newUser);
                    this.clearForm();
                if(result == 1) {
                    JOptionPane.showMessageDialog(this, "new user data create successfully", "success", JOptionPane.INFORMATION_MESSAGE);
                    loadUsers();
                }else {
                    JOptionPane.showMessageDialog(this, "Error occured while inserting data", "error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "Error occured while inserting data " +e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addSubmitMouseClicked

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        int selectedRow = usersTable.getSelectedRow();
        if (selectedRow != -1) {
            selectedUserId = Integer.parseInt(usersTable.getValueAt(selectedRow, 0).toString());
            fNameTexted.setText(usersTable.getValueAt(selectedRow, 1).toString());
            lNameTexted.setText(usersTable.getValueAt(selectedRow, 2).toString());
            emailTexted.setText(usersTable.getValueAt(selectedRow, 3).toString());
            countryTexted.setText(usersTable.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_usersTableMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        String firstName = fNameTexted.getText();
        String lastName = lNameTexted.getText();
        String email = emailTexted.getText();
        String country = countryTexted.getText();

    if (selectedUserId == -1) {
        JOptionPane.showMessageDialog(this, "No user selected!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else if(firstName.isEmpty()){
            JOptionPane.showMessageDialog(this, "first name is required", "error", JOptionPane.ERROR_MESSAGE);
    } else if(lastName.isEmpty()){
        JOptionPane.showMessageDialog(this, "last name is required", "error", JOptionPane.ERROR_MESSAGE);
    } else if(email.isEmpty()){
        JOptionPane.showMessageDialog(this, "email is required", "error", JOptionPane.ERROR_MESSAGE);
    }else if(country.isEmpty()){
        JOptionPane.showMessageDialog(this, "country is required", "error", JOptionPane.ERROR_MESSAGE);
    }else {
        UserModel updatedUser = new UserModel(selectedUserId, firstName, lastName, email, country);
        try {
            UserDAO userDao = new UserDAO();
            boolean success = userDao.updateUser(updatedUser);
            if (success) {
                JOptionPane.showMessageDialog(this, "User updated successfully.");
                loadUsers();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
       if(selectedUserId != -1) {
            int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this","Dialog", JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
                UserDAO userDAO;
                try{
                    userDAO = new UserDAO();
                    userDAO.deleteUser(selectedUserId);
                    JOptionPane.showMessageDialog(this,"Delete user data successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.clearForm();
                    loadUsers();
                    selectedUserId = -1;
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this,"Error while Deleted user data " + e, "Eror", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else{
            JOptionPane.showMessageDialog(this,"No data selected for delete user data", "Eror", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubmit;
    private javax.swing.JTextField countryTexted;
    private javax.swing.JButton delete;
    private javax.swing.JTextField emailTexted;
    private javax.swing.JTextField fNameTexted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameTexted;
    private javax.swing.JButton update;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
